### ISSUE TITLE
[Feature] auto-detect tree type

### ISSUE THREAD

**Issue by Nico04** [helightdev/dogs#24]
**Feature**
Given :
`final List<LandPropertyBase> properties = ...;`

This code throws 
`dogs.toJson(properties);`

`No converter found for type List<LandPropertyBase>`

While this code works fine 
`dogs.toJson(properties, tree: TypeTree.list())`

While it was no that easy for me to guess that, I still don't understand why it's needed : with json_serializable, iterable are natively handled, it's completly transparent. Couldn't the List type be detected automatically ?

**Comment by helightdev** [comment]
This should work now for dogs: ^10.1.0

**Comment by Nico04** [comment]
Thanks for the quick fix, however it doesn't fix the isssue.
Looking a the commit, it seems you added `(T == dynamic && type == null)` case, but my case, T is actually defined.
It's implicit, but static analysis shows type and when debugging, T is defined :

<img width="613" height="281" alt="Image" src="https://github.com/user-attachments/assets/4ee90290-9252-4955-92dc-16d0d424d0a5" />

<img width="691" height="898" alt="Image" src="https://github.com/user-attachments/assets/d4d4d4c6-f587-4f3c-a156-7252984b03ea" />

**Comment by Nico04** [comment]
It's probably linked, I have similar issue using

`dogs.fromNative<List<LandPropertyBase>>();`

throws

`Exception: No converter found for type List<LandPropertyBase>`

This code works

`dogs.fromNative<List<LandPropertyBase>>(j, tree: TypeTree.list<LandPropertyBase>())`

From my user point of view, the tree argument shouldn't be needed, don't you think ?
